FLAG_GENERIC_DATA = bytes.fromhex("00")
FLAG_CONFIRMATION = bytes.fromhex("80")
FLAG_END = bytes.fromhex("40")
FLAG_ACK = 0
FLAG_DATA = 1

SYNC_BYTES = bytes.fromhex("DCC023C2")
BYTE_ORDER = "big"

MAX_16BIT = 0xFFFF
PAD_BYTE = b"\x00"
SOCKET_TIMEOUT = 0.55

MAX_PAYLOAD_SIZE = 4096
FRAME_OVERHEAD = 120
MAX_FRAME_SIZE = MAX_PAYLOAD_SIZE + FRAME_OVERHEAD

MESSAGE_END = b"\n"
EMPTY_DATA = b""



